#assumes PWD is root of this project
version: '3'

services:

  spa:
    container_name: spa
    depends_on:
      - mysql
    image: zefiber/spa
    restart: always
    ports:
      - "9090:9090"
      - "5008:5008"

    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  mysql:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'starwar'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
